import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

import { getServerSession } from 'next-auth';
import SessionProvider from '@/app/components/SessionProvider';
import AuthButton from './components/AuthButton';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  console.log(`the session`, session);

  return (
    <html lang='en' data-theme='dark'>
      <body className={inter.className}>
        <SessionProvider session={session}>
          {/* <AuthButton /> */}
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
